Bugfix:   AttributeError: 'list' object has no attribute 'get'   context was a list instead of a dict   resolution: use 'read' method instead of 'browse'